# This is a basic workflow that is manually triggered

name: Spell checker

on: 
  push:
  pull_request:
    branches:
      - master
    
jobs:
  check:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Check spelling
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: npm install, build and test
      run: |
        npm install
        node action.js
